# Generated by Django 2.0.5 on 2018-07-31 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(max_length=100)),
                ('reason2', models.CharField(max_length=100)),
                ('reason3', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
