# Generated by Django 2.0.5 on 2018-07-31 00:46

from django.db import migrations

def seed(apps, schema_editor):
    Entry = apps.get_model('gratitude', 'Entry')
  
    Entry(reason1='Fidget Spinners', reason2='hello', reason3='reason 3', goal='this is my goal').save()
    Entry(reason1='Block Chain', reason2='reason 2', reason3='reason 3', goal='a new goal').save()
    Entry(reason1='Silly Bandz', reason2='reson', reason3='reson', goal='big goal').save()
    Entry(reason1='iPods', reason2='reason', reason3='reson', goal='goal').save()
    Entry(reason1='Myspace', reason2='reson', reason3='reson', goal='goal').save()
    Entry(reason1='JNCOs', reason2='reason', reason3='reson', goal='goal').save()
def fallow(apps, schema_editor):
    Entry = apps.get_model('gratitude', 'Entry')
    Entry.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
