# Generated by Django 2.0.5 on 2018-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0005_auto_20180802_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.IntegerField(),
        ),
    ]
