# Generated by Django 2.0.5 on 2018-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0008_auto_20180802_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.IntegerField(),
        ),
    ]
