# Generated by Django 2.0.5 on 2018-08-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0010_auto_20180812_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.IntegerField(),
        ),
    ]
