# Generated by Django 2.0.5 on 2018-08-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0012_auto_20180814_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.IntegerField(),
        ),
    ]
