# Generated by Django 2.0.5 on 2018-08-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gratitude', '0013_auto_20180814_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
