### login user
POST {{host}}/token-auth/ HTTP/1.1
Content-Type: application/json

{
    "username": "Test",
    "password": "test"
}
### get current user
GET {{host}}/gratitude/current_user/ HTTP/1.1
Authorization: jwt {{token}}

###